import 'package:flutter/cupertino.dart';

List<String> bloodKinds = [
  'A+',
  'A-',
  'B+',
  'B-',
  'O+',
  'O-',
  'AB+',
  'AB-',
];

Map<String, dynamic> animals = {
  "activity": "animals",
  "names": [
    "Ant",
    "Bear",
    "Crocodile",
    "Dog",
    "Elephent",
    "Fox",
    "Giraffe",
    "Horse",
    "Iguana",
    "Jellyfish",
    "Kongaro",
    "Lion",
    "Monkey",
    "Numbat",
    "Owl",
    "Pinguin",
    "Quail",
    "Rooster",
    "Sheep",
    "Tigger",
    "Unicorn",
    "Vulture",
    "Whale",
    "Xenops",
    "Yak",
    "Zebra"
  ],
  "pictures": [
    "assets/D21/images/images_animal/Ant.png",
    "assets/D21/images/images_animal/Bear.png",
    "assets/D21/images/images_animal/Crocodile.png",
    "assets/D21/images/images_animal/Dog.png",
    "assets/D21/images/images_animal/Elephent.png",
    "assets/D21/images/images_animal/Fox.png",
    "assets/D21/images/images_animal/Giraffe.png",
    "assets/D21/images/images_animal/Horse.png",
    "assets/D21/images/images_animal/Iguana.png",
    "assets/D21/images/images_animal/Jellyfish.png",
    "assets/D21/images/images_animal/Kongaro.png",
    "assets/D21/images/images_animal/Lion.png",
    "assets/D21/images/images_animal/Monkey.png",
    "assets/D21/images/images_animal/Numbat.png",
    "assets/D21/images/images_animal/Owl.png",
    "assets/D21/images/images_animal/Pinguin.png",
    "assets/D21/images/images_animal/Quail.png",
    "assets/D21/images/images_animal/Rooster.png",
    "assets/D21/images/images_animal/Sheep.png",
    "assets/D21/images/images_animal/Tigger.png",
    "assets/D21/images/images_animal/Unicorn.png",
    "assets/D21/images/images_animal/Vulture.png",
    "assets/D21/images/images_animal/Whale.png",
    "assets/D21/images/images_animal/Xenops.png",
    "assets/D21/images/images_animal/Yak.png",
    "assets/D21/images/images_animal/Zebra.png"
  ],
  "sounds": [
    "assets/D21/sounds/sounds_animal/ant.mp3",
    "assets/D21/sounds/sounds_animal/bear.mp3",
    "assets/D21/sounds/sounds_animal/crocodile.mp3",
    "assets/D21/sounds/sounds_animal/dog.mp3",
    "assets/D21/sounds/sounds_animal/elephent.mp3",
    "assets/D21/sounds/sounds_animal/fox.mp3",
    "assets/D21/sounds/sounds_animal/giraffe.mp3",
    "assets/D21/sounds/sounds_animal/horse.mp3",
    "assets/D21/sounds/sounds_animal/iguana.mp3",
    "assets/D21/sounds/sounds_animal/jellyfish.mp3",
    "assets/D21/sounds/sounds_animal/kongaro.mp3",
    "assets/D21/sounds/sounds_animal/lion.mp3",
    "assets/D21/sounds/sounds_animal/monkey.mp3",
    "assets/D21/sounds/sounds_animal/numbat.mp3",
    "assets/D21/sounds/sounds_animal/owl.mp3",
    "assets/D21/sounds/sounds_animal/pinguin.mp3",
    "assets/D21/sounds/sounds_animal/quail.mp3",
    "assets/D21/sounds/sounds_animal/rooster.mp3",
    "assets/D21/sounds/sounds_animal/sheep.mp3",
    "assets/D21/sounds/sounds_animal/tiger.mp3",
    "assets/D21/sounds/sounds_animal/unicorn.mp3",
    "assets/D21/sounds/sounds_animal/vulture.mp3",
    "assets/D21/sounds/sounds_animal/whale.mp3",
    "assets/D21/sounds/sounds_animal/xenops.mp3",
    "assets/D21/sounds/sounds_animal/yak.mp3",
    "assets/D21/sounds/sounds_animal/zebra.mp3"
  ],
  "questions": [
    {
      "text": "What is the name of this animals",
      "answer": "assets/D21/images/images_animal/Ant.png",
      "options": [
        "assets/D21/images/images_animal/Ant.png",
        "assets/D21/images/images_animal/Bear.png",
        "assets/D21/images/images_animal/Crocodile.png"
      ]
    }
  ]
};

Map<String, dynamic> alphapets = {
  "activity": "alphabet",
  "alpha": [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z"
  ],
  "words": [
    "apple",
    "ball",
    "cat",
    "duck",
    "elephant",
    "fish",
    "grapes",
    "hat",
    "iguana",
    "jelly",
    "key",
    "lion",
    "moon",
    "nest",
    "orange",
    "pig",
    "quail",
    "rocket",
    "snake",
    "turtle",
    "umbrella",
    "volcano",
    "watermelon",
    "xylophone",
    "yoyo",
    "zebra"
  ],
  "pictures": [
    "assets/Database/Database/char/alphabet/a.png",
    "assets/Database/Database/char/alphabet/b.png",
    "assets/Database/Database/char/alphabet/c.png",
    "assets/Database/Database/char/alphabet/d.png",
    "assets/Database/Database/char/alphabet/e.png",
    "assets/Database/Database/char/alphabet/f.png",
    "assets/Database/Database/char/alphabet/g.png",
    "assets/Database/Database/char/alphabet/h.png",
    "assets/Database/Database/char/alphabet/i.png",
    "assets/Database/Database/char/alphabet/j.png",
    "assets/Database/Database/char/alphabet/k.png",
    "assets/Database/Database/char/alphabet/l.png",
    "assets/Database/Database/char/alphabet/m.png",
    "assets/Database/Database/char/alphabet/n.png",
    "assets/Database/Database/char/alphabet/o.png",
    "assets/Database/Database/char/alphabet/p.png",
    "assets/Database/Database/char/alphabet/r.png",
    "assets/Database/Database/char/alphabet/s.png",
    "assets/Database/Database/char/alphabet/t.png",
    "assets/Database/Database/char/alphabet/u.png",
    "assets/Database/Database/char/alphabet/v.png",
    "assets/Database/Database/char/alphabet/w.png",
    "assets/Database/Database/char/alphabet/x.png",
    "assets/Database/Database/char/alphabet/y.png",
    "assets/Database/Database/char/alphabet/z.png"
  ],
  "shape": [
    "assets/Database/Database/char/images/apple.png",
    "assets/Database/Database/char/images/ball.png",
    "assets/Database/Database/char/images/cat.png",
    "assets/Database/Database/char/images/duck.png",
    "assets/Database/Database/char/images/elephant.png",
    "assets/Database/Database/char/images/fish.png",
    "assets/Database/Database/char/images/grapes.png",
    "assets/Database/Database/char/images/hat.png",
    "assets/Database/Database/char/images/jelly.png",
    "assets/Database/Database/char/images/key.png",
    "assets/Database/Database/char/images/lion.png",
    "assets/Database/Database/char/images/moon.png",
    "assets/Database/Database/char/images/nest.png",
    "assets/Database/Database/char/images/orange.png",
    "assets/Database/Database/char/images/pig.png",
    "assets/Database/Database/char/images/quail.png",
    "assets/Database/Database/char/images/rocket.png",
    "assets/Database/Database/char/images/snake.png",
    "assets/Database/Database/char/images/turtle.png",
    "assets/Database/Database/char/images/umbrella.png",
    "assets/Database/Database/char/images/volcano.png",
    "assets/Database/Database/char/images/watermelon.png",
    "assets/Database/Database/char/images/xylophone.png",
    "assets/Database/Database/char/images/yoyo.png",
    "assets/Database/Database/char/images/zebra.png"
  ],
  "Voice": [
    "assets/Database/Database/char/Voice/A_apple.mp3",
    "assets/Database/Database/char/Voice/B_ball.mp3",
    "assets/Database/Database/char/Voice/C_cat.mp3",
    "assets/Database/Database/char/Voice/D_duck.mp3",
    "assets/Database/Database/char/Voice/E_elephant.mp3",
    "assets/Database/Database/char/Voice/F_fish.mp3",
    "assets/Database/Database/char/Voice/G_grapes.mp3",
    "assets/Database/Database/char/Voice/H_hat.mp3",
    "assets/Database/Database/char/Voice/I_ice cream.mp3",
    "assets/Database/Database/char/Voice/J_jelly.mp3",
    "assets/Database/Database/char/Voice/K_key.mp3",
    "assets/Database/Database/char/Voice/L_lion.mp3",
    "assets/Database/Database/char/Voice/M_moon.mp3",
    "assets/Database/Database/char/Voice/N_nest.mp3",
    "assets/Database/Database/char/Voice/O_orange.mp3",
    "assets/Database/Database/char/Voice/R_rocket.mp3",
    "assets/Database/Database/char/Voice/S_snake.mp3",
    "assets/Database/Database/char/Voice/T_turtle.mp3",
    "assets/Database/Database/char/Voice/U_umbrella.mp3",
    "assets/Database/Database/char/Voice/V_volcano.mp3",
    "assets/Database/Database/char/Voice/W_watermelon.mp3",
    "assets/Database/Database/char/Voice/X_xylophone.mp3",
    "assets/Database/Database/char/Voice/Y_yoyo.mp3",
    "assets/Database/Database/char/Voice/Z_zebra.mp3"
  ]
};

Map<String, dynamic> numbers = {
  "activity": "number",
  "names": [
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "thirteen",
    "fourteen",
    "fifteen",
    "sixteen",
    "seventeen",
    "eighteen",
    "nineteen",
    "twenty"
  ],
  "pictures": [
    "assets/D21/images/images_number/1.svg",
    "assets/D21/images/images_number/2.svg",
    "assets/D21/images/images_number/3.svg",
    "assets/D21/images/images_number/4.svg",
    "assets/D21/images/images_number/5.svg",
    "assets/D21/images/images_number/6.svg",
    "assets/D21/images/images_number/7.svg",
    "assets/D21/images/images_number/8.svg",
    "assets/D21/images/images_number/9.svg",
    "assets/D21/images/images_number/10.svg",
    "assets/D21/images/images_number/11.svg",
    "assets/D21/images/images_number/12.svg",
    "assets/D21/images/images_number/13.svg",
    "assets/D21/images/images_number/14.svg",
    "assets/D21/images/images_number/15.svg",
    "assets/D21/images/images_number/16.svg",
    "assets/D21/images/images_number/17.svg",
    "assets/D21/images/images_number/18.svg",
    "assets/D21/images/images_number/19.svg",
    "assets/D21/images/images_number/20.svg"
  ],
  "sounds": [
    "assets/D21/sounds/sounds_number/1.mp3",
    "assets/D21/sounds/sounds_number/2.mp3",
    "assets/D21/sounds/sounds_number/3.mp3",
    "assets/D21/sounds/sounds_number/4.mp3",
    "assets/D21/sounds/sounds_number/5.mp3",
    "assets/D21/sounds/sounds_number/6.mp3",
    "assets/D21/sounds/sounds_number/7.mp3",
    "assets/D21/sounds/sounds_number/8.mp3",
    "assets/D21/sounds/sounds_number/9.mp3",
    "assets/D21/sounds/sounds_number/10.mp3",
    "assets/D21/sounds/sounds_number/11.mp3",
    "assets/D21/sounds/sounds_number/12.mp3",
    "assets/D21/sounds/sounds_number/13.mp3",
    "assets/D21/sounds/sounds_number/14.mp3",
    "assets/D21/sounds/sounds_number/15.mp3",
    "assets/D21/sounds/sounds_number/16.mp3",
    "assets/D21/sounds/sounds_number/17.mp3",
    "assets/D21/sounds/sounds_number/18.mp3",
    "assets/D21/sounds/sounds_number/19.mp3",
    "assets/D21/sounds/sounds_number/20.mp3"
  ],
  "questions": [
    {
      "text": "how many apples are there ?",
      "kind": "text",
      "pic": "assets/D21/images/images_fruits/apple.png",
      "answer": "1",
      "options": ["3", "1", "5"]
    },
    {
      "text": "which one of these represents 7 triangles",
      "answer": "assets/D21/images/images_pictures/7/right.png",
      "kind": "pic",
      "pic": "",
      "options": [
        "assets/D21/images/images_pictures/7/right.png",
        "assets/D21/images/images_pictures/7/wrong.png"
      ]
    },
    {
      "text": "how many dots are on the frame ?",
      "kind": "text",
      "pic": "assets/D21/images/images_pictures/dots/dots.png",
      "answer": "6",
      "options": ["3", "6", "5", "7", "10", "0"]
    },
    {
      "text": "how do you write {eighy} by digit ?",
      "answer": "8",
      "kind": "text",
      "pic": "",
      "options": ["3", "6", "8", "7", "10", "0"]
    },
    {
      "text": "how many watermelons are there ?",
      "pic": "assets/D21/images/images_fruits/apple.png",
      "answer": "3",
      "kind": "text",
      "options": ["3", "1", "5", "10", "0"]
    },
    {
      "text": "which number is larger ?",
      "answer": "7",
      "pic": "",
      "kind": "text",
      "options": ["5", "7"]
    },
    {
      "kind": "text",
      "text": "which number is smaller ?",
      "answer": "0",
      "pic": "",
      "options": ["0", "8"]
    },
    {
      "kind": "pic",
      "text": "which one of these is more ?",
      "answer": "assets/D21/images/images_pictures/7/right.png",
      "pic": "",
      "options": [
        "assets/D21/images/images_pictures/7/right.png",
        "assets/D21/images/images_pictures/7/wrong.png"
      ]
    },
    {
      "kind": "text",
      "text": "Count the tally marks. What number is shown?",
      "pic": "assets/D21/images/images_pictures/tally/tally.png",
      "answer": "5",
      "options": ["3", "1", "5", "10", "0"]
    },
    {
      "kind": "text",
      "text": "how many cubes are there ?",
      "pic": "assets/D21/images/images_pictures/cubes/cubes.png",
      "answer": "6",
      "options": ["3", "6", "5", "10", "0"]
    }
  ]
};

Color mainColor = const Color(0xff1CB0F6);

String aboutUs =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

String healthyFood =
    'The American Academy of Pediatrics’ Committee on Genetics has noted that those with Down syndrome are likely to develop certain health problems. This is thought to happen as a result of body structures not developing normally.Children with Down syndrome are likely to be overweight and have a higher risk of obesity. They burn calories at a slower rate and are frequently diagnosed with an under-active thyroid which can contribute to weight gain.Gastroesophageal reflux disease (GERD) is common among children with Down syndrome.Symptoms include heartburn, sore throat, regurgitation and chest pain.Gluten intolerance and celiac disease is also widespread and can lead to nutrient deficiency and an impaired immune system if dietary needs are avoided.Finally, periodontal disease becomes prevalent in adulthood so it is important to establish habits to eat foods that will decrease its likelihood.';
